version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: etl_zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      4LW_COMMANDS_WHITELIST: "ruok,stat"
    ports:
      - "2182:2181"
    networks:
      - kafka-cassandra-network
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: etl_kafka-container
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - kafka-cassandra-network
    restart: unless-stopped

  cassandra:
    image: cassandra:latest
    container_name: etl-cassandra-container
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_LISTEN_ADDRESS=etl-cassandra-container
      - CASSANDRA_BROADCAST_ADDRESS=etl-cassandra-container
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      kafka-cassandra-network:
        aliases:
          - cassandra
    restart: unless-stopped

volumes:
  cassandra-data:

networks:
  kafka-cassandra-network:
    driver: bridge
